# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: 'Xu Jin - Resume' # Website name
baseURL: 'https://xujin.work' # Website URL

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart
timeout: 600000
taxonomies:
  author: authors
markup:
  _merge: deep
  highlight:
    lineNos: false
  goldmark:
    renderer:
      unsafe: true
security:
  _merge: deep
  enableInlineShortcodes: true
  funcs:
    getenv:
      - ^HUGO_
      - ^WC_
  http:
    methods:
      - (?i)GET|POST
    urls:
      - .*
sitemap:
  _merge: deep

# 缓存配置 - GitHub Pages部署需要
caches:
  images:
    dir: :cacheDir/images

# 忽略警告
ignoreLogs: ['warning-goldmark-raw-html']